imomi_azam/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls', namespace='mainapp')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from.import views

app_name = 'mainapp'

urlpatterns = [
	path('',views.index, name='Home'),
	path('about/',views.about, name='About'),
	path('about/<str:sheikh_slug>',views.scholar, name='scholarDetailPage'),
	path('blog/',views.blog, name='Blog'),
	path('contact/',views.contact, name='Contact'),
	path('gallery/',views.gallery, name='gallery'),
	path('audio/',views.audio, name='audio'),
	path('blog/<str:blog_slug>',views.blog_detail, name='blogDetailPage'),
	path('ramadan/',views.ramadan, name='ramadan'),
]

mainapp/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Namaz_time(models.Model):
	name = models.CharField('Namoz nomi', max_length=100)
	time = models.CharField('Namoz vaqti', max_length=100)

	class Meta:
		verbose_name = 'Namoz vaqti'
		verbose_name_plural = 'Namoz vaqtlari'

	def __str__(self):
		return f"{self.name}"

class Blog(models.Model):
	title = models.CharField('Maqola nomi',max_length=300)
	body = RichTextField()
	slug = models.SlugField('*',max_length=100, unique=True, db_index=True)
	author = models.CharField('Muallif', default='Admin',max_length=200,blank=True)
	date = models.DateField("Qo'shilgan vaqti", auto_now_add=True)
	image = models.ImageField('Maqola rasmi', upload_to='Maqolalar_rasmi/')

	class Meta:
		verbose_name = 'Maqola'
		verbose_name_plural = 'Maqolalar'

	def get_absalute_url(self):   
		return reverse('mainapp:blogDetailPage',kwargs={'blog_slug':self.slug})

	def __str__(self):
		return f'{self.title}'

class Comment(models.Model):
	blog_page = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
	name = models.CharField('Ismi', max_length=50)
	message = models.TextField('Xabar',)

	class  Meta:
		verbose_name = 'Muhokama'
		verbose_name_plural = 'Muhokamalar'

	def __str__(self):
		return f"{self.name}"

class Sheikhs(models.Model):
	slug = models.SlugField('*',max_length=200, unique=True, db_index=True)
	name = models.CharField('Ismi', max_length=200)
	direction = models.CharField("Yo'nalishi", max_length=200)
	fullname = models.CharField('Toliq ismi',max_length=300)
	surname = models.CharField("familiyasi",max_length=300)
	address = models.CharField('Yashash manzili',max_length=500)
	phone = models.CharField('Telfon raqami',max_length=100)
	about = models.TextField("To'liq malumoti")
	image = models.ImageField('Rasmi',upload_to='Sheikhs/')

	class Meta:
		verbose_name = 'Qori va Imom'
		verbose_name_plural = 'Qorilar va Imomlar'

	def get_absalute_url(self):
		return reverse('mainapp:scholarDetailPage',kwargs={'sheikh_slug':self.slug})
	def __str__(self):
		return f'{self.name}'

class Gallery(models.Model):
	title = models.CharField('Rasm matni',max_length=200,default='Imomi Azazm Rahmutullohi alayh jome masjid')
	date = models.DateField('Joylangan vaqti',auto_now_add=True)
	images = models.ImageField('Rasmi',upload_to='Gallerys/')

	class Meta:
		verbose_name = 'Rasim'
		verbose_name_plural = 'Rasmlar'

	def __str__(self):
		return f"{self.title}"

class Audio(models.Model):
	audio_name = models.CharField('Sura nomi',max_length=250)
	audio_img = models.ImageField(upload_to='Audio_files/')
	audio_files = models.FileField('Audioni yuklash')

	class Meta:
		verbose_name = "Audio"
		verbose_name_plural = "Audiolar"
	def __str__(self):
		return f"{self.audio_name}"

class Contact(models.Model):
	name = models.CharField("F,I,SH",max_length=250)
	email = models.EmailField('Elektron pochta',max_length=100)
	phone = models.CharField("Telfon raqami",max_length=20)
	message = models.TextField("Xabari")

	class Meta:
		verbose_name = "Aloqa"
		verbose_name_plural = "Aloqalar"
	def __str__ (self):
		return f'{self.name}'

mainapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from.models import*
from django.contrib import messages
import telebot
from bs4 import BeautifulSoup
import requests
from datetime import datetime

me = 696007117
TOKEN = '1934423453:AAH-gOkWjUH0jZn6cd40tU0rfsI2ZGeRuMA'
bot = telebot.TeleBot(TOKEN)

def customHandler404(request, exception=None):
    return render(request, '404.html')

def contact(request):
	if request.method == 'POST':
		name = request.POST['name']
		email = request.POST['email']
		phone = request.POST['phone']
		message = request.POST['message']
		Contact.objects.create(
			name=name,
			email=email,
			phone=phone,
			message=message,
			),
		messages.add_message(request, messages.SUCCESS, 'Tabriklaymiz aloqa muofaqiyat amalga oshirildi tez orada sayit adminlari sizbilan bog\'lanishadi')
		bot.send_message(me,f"Aloqa xizmatidan xabar bor\nIsmi:  {name}\nTelfon raqami:  {phone}\nEmail:  {email}\n Xabari:  {message}")
	return render(request,'contact.html')

def index(request):
	times = Namaz_time.objects.all()
	blog = Blog.objects.all().order_by('-id')[:3]
	url = 'https://islom.uz/'
	page = requests.get(url)
	soup = BeautifulSoup(page.text, "html.parser")
	time = soup.findAll('div', class_='date_time')
	time_now = datetime.now()
	for i in time:
	    t = i.text
	    time[0] = t
	    time = time[0]
	timer = {
	    'now': time_now.strftime("%H:%M:%S")
}
	context = {
	'times':times,
	'blog':blog,
	'time':time,
	'timer':timer['now']
	}
	return render(request,'index2.html',context)


def blog(request):
	blog = Blog.objects.all().order_by("-id")[:10]
	return render(request,'blog.html',{'blog':blog})

def blog_detail(request,blog_slug):
	blog_page = Blog.objects.get(slug=blog_slug)
	if request.method == "POST":
		name = request.POST['name']
		message = request.POST['message']
		comment = Comment.objects.create(
			name=name,
			message=message,)
		comment.blog_page = blog_page
		comment.save()

		bot.send_message(me,f"Commentaryiadan xabar bor\nIsmi:  {name}  \n Xabari:  {message}")
	return render(request,'blog-detail.html',{'blog_page':blog_page})

def about(request):
	sheikh = Sheikhs.objects.all()
	return render(request,'about.html',{'sheikh':sheikh})


def gallery(request):
	gallery = Gallery.objects.all()
	return render(request,'gallery2.html',{'gallery':gallery})

def audio(request):
	audio = Audio.objects.all().order_by("-id")
	paginator = Paginator(audio, 10) 
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	return render(request,'audio-listening.html',{'audio':audio,'page_obj': page_obj})

def scholar(request,sheikh_slug):
	sheikh = Sheikhs.objects.get(slug=sheikh_slug)
	return render(request,'scholar-detail.html',{'sheikh':sheikh})

def ramadan(request):
	return render(request,'donation-detail.html')

templates/audio-listening.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
            <section>
                <div class="w-100 pt-80 black-layer pb-70 opc65 position-relative">
                    <div class="fixed-bg" style="background-image: url(https://lifeglobe.net/x/entry/2330/enlightening_by_el3sl.jpg);"></div>
                    <div class="container">
                        <div class="page-title-wrap text-center w-100">
                            <div class="page-title-inner d-inline-block">
                                <h1 class="mb-0"> АУДИО ҚУРЪОН ТИНГЛАНГ</h1>
                                <ol class="breadcrumb mb-0">
                                    <li class="breadcrumb-item"><a href="{% url 'mainapp:Home' %}" title="Home">Масжид - Бош саҳифа</a></li>
                                    <li class="breadcrumb-item active">АУДИО ҚУРЪОН </li>
                                </ol>
                            </div>
                        </div><!-- Page Title Wrap -->
                    </div>
                </div>
            </section>
            <section>
                <div class="w-100 pt-120 pb-250 position-relative">
                    <img class="sec-botm-rgt-mckp img-fluid position-absolute" src="/static/assets/images/sec-botm-mckp.png" alt="Sec Bottom Mockup">
                    <div class="container">
                        {%for audios in audio %}
                        <div class="plyr-wrp2 d-inline-block w-100">
                            <div class="plyr-box w-100 pat-bg white-layer opc85 back-blend-multiply bg-white" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                <div class="plyr v4 w-100">
                                    <ul class="playlist mb-0 list-unstyled">
                                        <li data-cover="{{audios.audio_img.url}}" data-artist=""><a href="{{audios.audio_files.url}}" title="">{{audios.audio_name}}</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- Player Wrap 2 -->
                        {%endfor%}
                     
                          <div class="pagination">
                            <span class="step-links">
                                {% if page_obj.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>

                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                        </div>
                      </div>
                    </div>  
                  </div>
                </div>
              </div>
                        </div><!-- Pagination Wrap -->
                    </div>
                </div>
            </section>
{%endblock%}

templates/donation-detail.html
{%extends 'base.html' %}
{%load static%}
{%block content%}


<div class="container">

</div>

{%endblock%}

templates/page404.html
<h1>XATO</h1>

templates/services.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
            <section>
                <div class="w-100 pt-80 black-layer pb-70 opc65 position-relative">
                    <div class="fixed-bg" style="background-image: url(/static/assets/images/page-title-bg.jpg);"></div>
                    <div class="container">
                        <div class="page-title-wrap text-center w-100">
                            <div class="page-title-inner d-inline-block">
                                <h1 class="mb-0">Хизматлар</h1>
                                <ol class="breadcrumb mb-0">
                                    <li class="breadcrumb-item"><a href="index.html" title="Home">Корабош-ота  Бош сахифа</a></li>
                                    <li class="breadcrumb-item active">Хизмат турлари</li>
                                </ol>
                            </div>
                        </div><!-- Page Title Wrap -->
                    </div>
                </div>
            </section>
            <section>
                <div class="w-100 pt-120 pb-280 position-relative">
                    <img class="sec-botm-rgt-mckp img-fluid position-absolute" src="/static/assets/images/sec-botm-mckp.png" alt="Sec Bottom Mockup">
                    <div class="container">
                        <div class="serv-wrap wide-sec">
                            <div class="row mrg10">
                                <div class="col-md-6 col-sm-6 col-lg-3">
                                    <div class="serv-box text-center pat-bg gray-layer opc8 position-relative back-blend-multiply gray-bg w-100" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                        <i class="flaticon-mat thm-clr"></i>
                                        <h3 class="mb-0">Help Poor's</h3>
                                        <p class="mb-0">Lorem ipsum dolor sit amet, coteudtu adipisicing elit, sed do eiusmod tem por incididunt ut labore et.</p>
                                        <a href="services-detail.html" title="">Read More</a>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-lg-3">
                                    <div class="serv-box text-center pat-bg gray-layer opc8 position-relative back-blend-multiply gray-bg w-100" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                        <i class="flaticon-minaret thm-clr"></i>
                                        <h3 class="mb-0">Mosque Development</h3>
                                        <p class="mb-0">Lorem ipsum dolor sit amet, coteudtu adipisicing elit, sed do eiusmod tem por incididunt ut labore et.</p>
                                        <a href="services-detail.html" title="">Read More</a>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-lg-3">
                                    <div class="serv-box text-center pat-bg gray-layer opc8 position-relative back-blend-multiply gray-bg w-100" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                        <i class="flaticon-grave thm-clr"></i>
                                        <h3 class="mb-0">Funeral Service</h3>
                                        <p class="mb-0">Lorem ipsum dolor sit amet, coteudtu adipisicing elit, sed do eiusmod tem por incididunt ut labore et.</p>
                                        <a href="services-detail.html" title="">Read More</a>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-lg-3">
                                    <div class="serv-box text-center pat-bg gray-layer opc8 position-relative back-blend-multiply gray-bg w-100" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                        <i class="flaticon-quran thm-clr"></i>
                                        <h3 class="mb-0">Quran Learning</h3>
                                        <p class="mb-0">Lorem ipsum dolor sit amet, coteudtu adipisicing elit, sed do eiusmod tem por incididunt ut labore et.</p>
                                        <a href="services-detail.html" title="">Read More</a>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-lg-3">
                                    <div class="serv-box text-center pat-bg gray-layer opc8 position-relative back-blend-multiply gray-bg w-100" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                        <i class="flaticon-arabic thm-clr"></i>
                                        <h3 class="mb-0">Community Service</h3>
                                        <p class="mb-0">Lorem ipsum dolor sit amet, coteudtu adipisicing elit, sed do eiusmod tem por incididunt ut labore et.</p>
                                        <a href="services-detail.html" title="">Read More</a>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-lg-3">
                                    <div class="serv-box text-center pat-bg gray-layer opc8 position-relative back-blend-multiply gray-bg w-100" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                        <i class="flaticon-hajj thm-clr"></i>
                                        <h3 class="mb-0">Special Child Care</h3>
                                        <p class="mb-0">Lorem ipsum dolor sit amet, coteudtu adipisicing elit, sed do eiusmod tem por incididunt ut labore et.</p>
                                        <a href="services-detail.html" title="">Read More</a>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-lg-3">
                                    <div class="serv-box text-center pat-bg gray-layer opc8 position-relative back-blend-multiply gray-bg w-100" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                        <i class="flaticon-cow thm-clr"></i>
                                        <h3 class="mb-0">Kurbani Service</h3>
                                        <p class="mb-0">Lorem ipsum dolor sit amet, coteudtu adipisicing elit, sed do eiusmod tem por incididunt ut labore et.</p>
                                        <a href="services-detail.html" title="">Read More</a>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-lg-3">
                                    <div class="serv-box text-center pat-bg gray-layer opc8 position-relative back-blend-multiply gray-bg w-100" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                        <i class="flaticon-quran-2 thm-clr"></i>
                                        <h3 class="mb-0">Quran Translation</h3>
                                        <p class="mb-0">Lorem ipsum dolor sit amet, coteudtu adipisicing elit, sed do eiusmod tem por incididunt ut labore et.</p>
                                        <a href="services-detail.html" title="">Read More</a>
                                    </div>
                                </div>
                            </div>
                        </div><!-- Services Wrap -->
                        <div class="pagination-wrap mt-60 d-flex flex-wrap justify-content-center text-center w-100">
                            <ul class="pagination mb-0">
                                <li class="page-item prev"><a class="page-link" href="javascript:void(0);" title=""><i class="fas fa-long-arrow-alt-left"></i></a></li>
                                <li class="page-item"><a class="page-link" href="javascript:void(0);" title="">1</a></li>
                                <li class="page-item active"><a class="page-link" href="javascript:void(0);" title="">2</a></li>
                                <li class="page-item"><a class="page-link" href="javascript:void(0);" title="">3</a></li>
                                <li class="page-item"><a class="page-link" href="javascript:void(0);" title="">4</a></li>
                                <li class="page-item pg-rang">...........</li>
                                <li class="page-item"><a class="page-link" href="javascript:void(0);" title="">24</a></li>
                                <li class="page-item next"><a class="page-link" href="javascript:void(0);" title=""><i class="fas fa-long-arrow-alt-right"></i></a></li>
                            </ul>
                        </div><!-- Pagination Wrap -->
                    </div>
                </div>
            </section>
{%endblock%}